server:
  port: 8060
management:
  endpoints:
    web:
      exposure:
        # Expose only what's necessary to reduce attack surface
        include: health, info, prometheus, metrics 
  endpoint:
    health:
      # Required for /actuator/health/liveness and /actuator/health/readiness
      probes:
        enabled: true
      # Shows details (like DB status) to help you debug why it's DOWN
      show-details: always 
      group:
        readiness:
          # Include readiness state + your actual dependencies
          include: readinessState
        liveness:
          # Keep liveness minimal so transient DB blips don't restart the pod
          include: livenessState
  server:
    port: 8061
spring:
  application:
    name: productgateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_8zoT6zRFr
          # OR use jwk-set-uri:
          jwk-set-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_8zoT6zRFr/.well-known/jwks.json
  cloud:
    gateway:
      #discovery:
        #locator:
         # enabled: true
          #lower-case-service-id: true
      routes:
        - id: cart-routs
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/cart/**
        - id: categories-rout
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/categories/**
        - id: product-category-mapping-routs
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/product-category-mapping/**
        - id: product-category-mapping-routs
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/product-category-mapping/**
        - id: product-catalog
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/products/**
          #filters:
          #  - RewritePath=/product/?(?<segment>.*), /${segment}
        - id: users-route
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/users/**
        - id: variant-route
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/variants/**
        - id: wishlist-route
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/wishlist/**
        - id: product-catalog-svc-swagger
          uri: http://productcatalogsvc:8050
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG
