apiVersion: v1
kind: Service
metadata:
  name: productgateway
  namespace: nagp-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: productgateway
  ports:
    - port: 8060
      targetPort: 8060
